localhub/communities/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    community_detail_view,
    community_terms_view,
    community_update_view,
    membership_delete_view,
    membership_detail_view,
    membership_leave_view,
    membership_list_view,
    membership_update_view,
)

app_name = "communities"

urlpatterns = [
    path("about/", view=community_detail_view, name="community_detail"),
    path("terms/", view=community_terms_view, name="community_terms"),
    path("~update/", view=community_update_view, name="community_update"),
    path("~leave/", view=membership_leave_view, name="membership_leave"),
    path("memberships/", view=membership_list_view, name="membership_list"),
    path(
        "memberships/<int:pk>/", view=membership_detail_view, name="membership_detail",
    ),
    path(
        "memberships/<int:pk>/~update/",
        view=membership_update_view,
        name="membership_update",
    ),
    path(
        "memberships/<int:pk>/~delete/",
        view=membership_delete_view,
        name="membership_delete",
    ),
]

localhub/join_requests/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    join_request_accept_view,
    join_request_create_view,
    join_request_delete_view,
    join_request_detail_view,
    join_request_list_view,
    join_request_reject_view,
    sent_join_request_list_view,
)

app_name = "join_requests"

urlpatterns = [
    path("", view=join_request_list_view, name="list"),
    path("sent/", view=sent_join_request_list_view, name="sent_list"),
    path("~create/", view=join_request_create_view, name="create"),
    path("<int:pk>/", view=join_request_detail_view, name="detail"),
    path("<int:pk>/~accept/", view=join_request_accept_view, name="accept"),
    path("<int:pk>/~reject/", view=join_request_reject_view, name="reject"),
    path("<int:pk>/~delete/", view=join_request_delete_view, name="delete"),
]

localhub/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from localhub.activities.views.streams import activity_stream_view
from localhub.communities.views import (
    community_list_view,
    community_not_found_view,
    community_sidebar_view,
    community_welcome_view,
)
from localhub.users.views import (
    dismiss_notice_view,
    switch_theme_view,
    user_delete_view,
    user_update_view,
)

urlpatterns = [
    # Local
    path("", view=activity_stream_view, name="activity_stream"),
    path("", include("localhub.activities.urls")),
    path("bookmarks/", include("localhub.bookmarks.urls")),
    path("comments/", include("localhub.comments.urls")),
    path("events/", include("localhub.events.urls")),
    path("flags/", include("localhub.flags.urls")),
    path("invites/", include("localhub.invites.urls")),
    path("join-requests/", include("localhub.join_requests.urls")),
    path("notifications/", include("localhub.notifications.urls")),
    path("favorites/", include("localhub.likes.urls")),
    path("messages/", include("localhub.private_messages.urls")),
    path("photos/", include("localhub.photos.urls")),
    path("polls/", include("localhub.polls.urls")),
    path("posts/", include("localhub.posts.urls")),
    path("people/", include("localhub.users.urls")),
    path("site/", include("localhub.communities.urls")),
    path("sites/", community_list_view, name="community_list"),
    path("account/~update", user_update_view, name="user_update"),
    path("account/~delete", user_delete_view, name="user_delete"),
    path("welcome/", view=community_welcome_view, name="community_welcome"),
    path("sidebar/", view=community_sidebar_view, name="community_sidebar"),
    path("not-found/", view=community_not_found_view, name="community_not_found"),
    path("~theme/<str:theme>/", switch_theme_view, name="switch_theme"),
    path("~dismiss-notice/<str:notice>/", dismiss_notice_view, name="dismiss_notice"),
    # Third-party
    path("account/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

# silk
if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:

    # debug toolbar
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # static views
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # allow preview/debugging of error views in development
    urlpatterns += [
        path("errors/400/", TemplateView.as_view(template_name="400.html")),
        path("errors/403/", TemplateView.as_view(template_name="403.html")),
        path("errors/404/", TemplateView.as_view(template_name="404.html")),
        path("errors/405/", TemplateView.as_view(template_name="405.html")),
        path("errors/500/", TemplateView.as_view(template_name="500.html")),
        path("errors/csrf/", TemplateView.as_view(template_name="403_csrf.html")),
    ]

localhub/join_requests/models.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from model_utils.fields import MonitorField
from model_utils.models import TimeStampedModel

from localhub.communities.models import Community
from localhub.db.search import SearchQuerySetMixin


class JoinRequestQuerySet(SearchQuerySetMixin, models.QuerySet):
    search_document_field = "sender__search_document"

    def for_sender(self, user):
        return self.filter(sender=user).exclude(community__members=user)

    def for_community(self, community):
        return self.filter(community=community)

    def pending(self):
        return self.filter(status=self.model.Status.PENDING)

    def accepted(self):
        return self.filter(status=self.model.Status.ACCEPTED)

    def rejected(self):
        return self.filter(status=self.model.Status.REJECTED)


class JoinRequest(TimeStampedModel):
    class Status(models.TextChoices):
        PENDING = "pending", _("Pending")
        ACCEPTED = "accepted", _("Accepted")
        REJECTED = "rejected", _("Rejected")

    community = models.ForeignKey(Community, on_delete=models.CASCADE)

    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    status = models.CharField(
        max_length=100, choices=Status.choices, default=Status.PENDING, db_index=True
    )
    status_changed = MonitorField(monitor="status")

    sent = models.DateTimeField(null=True, blank=True)

    intro = models.TextField(
        blank=True,
        verbose_name=_("Introduction"),
        help_text=_(
            "Tell us a little bit about yourself and why you "
            "would like to join this community (Optional)."
        ),
    )

    objects = JoinRequestQuerySet.as_manager()

    class Meta:
        unique_together = ("community", "sender")
        indexes = [models.Index(fields=["status"])]

    def __str__(self):
        return str(self.sender)

    def get_absolute_url(self):
        return reverse("join_requests:detail", args=[self.id])

    def is_pending(self):
        return self.status == self.Status.PENDING

    def is_accepted(self):
        return self.status == self.Status.ACCEPTED

    def is_rejected(self):
        return self.status == self.Status.REJECTED

    def accept(self):
        self.status = JoinRequest.Status.ACCEPTED
        self.save()

    def reject(self):
        self.status = JoinRequest.Status.REJECTED
        self.save()

localhub/communities/views/base.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CommunityRequiredMixin(LoginRequiredMixin):
    """
    Ensures that a community is available on this domain. This requires
    the CurrentCommunityMiddleware is enabled.

    If the user is not a member they will be redirected to the Welcome view.

    If the view has the `allow_non_members` property *True* then the above
    rule is overriden - for example in some cases where we want to allow
    the user to be able to handle an invitation.
    """

    allow_non_members = False

    def dispatch(self, request, *args, **kwargs):
        if not request.community.active:
            return self.handle_community_not_found()

        if (
            request.user.is_authenticated
            and not request.user.has_perm(
                "communities.view_community", request.community
            )
            and not self.allow_non_members
        ):
            return self.handle_community_access_denied()
        return super().dispatch(request, *args, **kwargs)

    def handle_community_access_denied(self):
        if self.request.is_ajax():
            raise PermissionDenied(_("You must be a member of this community"))
        return HttpResponseRedirect(reverse("community_welcome"))

    def handle_community_not_found(self):
        if self.request.is_ajax():
            raise Http404(_("No community is available for this domain"))
        return HttpResponseRedirect(reverse("community_not_found"))

localhub/join_requests/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Case, IntegerField, Value, When
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from rules.contrib.views import PermissionRequiredMixin
from vanilla import CreateView, DeleteView, DetailView, GenericModelView, ListView

from localhub.communities.models import Membership
from localhub.communities.views import CommunityRequiredMixin
from localhub.views import SearchMixin, SuccessMixin

from .emails import send_acceptance_email, send_join_request_email, send_rejection_email
from .forms import JoinRequestForm
from .models import JoinRequest


class JoinRequestQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return JoinRequest.objects.for_community(self.request.community)


class JoinRequestManageMixin(PermissionRequiredMixin, JoinRequestQuerySetMixin):
    permission_required = "communities.manage_community"

    def get_permission_object(self):
        return self.request.community


class JoinRequestListView(JoinRequestManageMixin, SearchMixin, ListView):
    paginate_by = settings.LOCALHUB_LONG_PAGE_SIZE
    model = JoinRequest

    @cached_property
    def status(self):
        status = self.request.GET.get("status")
        if status in JoinRequest.Status.values and self.total_count:
            return status
        return None

    @cached_property
    def status_display(self):
        return dict(JoinRequest.Status.choices)[self.status] if self.status else None

    @cached_property
    def total_count(self):
        return super().get_queryset().count()

    def get_queryset(self):
        qs = super().get_queryset().select_related("community", "sender")
        if self.search_query:
            qs = qs.search(self.search_query)

        if self.status:
            qs = qs.filter(status=self.status).order_by("-created")
        else:
            qs = qs.annotate(
                priority=Case(
                    When(status=JoinRequest.Status.PENDING, then=Value(1)),
                    default_value=0,
                    output_field=IntegerField(),
                )
            ).order_by("priority", "-created")
        return qs

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data.update(
            {
                "total_count": self.total_count,
                "status": self.status,
                "status_display": self.status_display,
                "status_choices": list(JoinRequest.Status.choices),
            }
        )
        return data


join_request_list_view = JoinRequestListView.as_view()


class JoinRequestDetailView(JoinRequestManageMixin, DetailView):
    model = JoinRequest


join_request_detail_view = JoinRequestDetailView.as_view()


class JoinRequestDeleteView(PermissionRequiredMixin, SuccessMixin, DeleteView):
    model = JoinRequest
    permission_required = "join_requests.delete"

    def get_queryset(self):
        return super().get_queryset().select_related("community", "sender")

    @cached_property
    def is_sender(self):
        return self.object.sender == self.request.user

    def get_success_url(self):
        if self.is_sender:
            if JoinRequest.objects.for_sender(self.request.user).exists():
                return reverse("join_requests:sent_list")
            return settings.LOCALHUB_HOME_PAGE_URL
        return reverse("join_requests:list")

    def get_success_message(self):
        if self.is_sender:
            return _("Your join request for %(community)s has been deleted") % {
                "community": self.object.community.name
            }
        return _("Join request for %(sender)s has been deleted") % {
            "sender": self.object.sender.get_display_name()
        }

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return self.success_response()


join_request_delete_view = JoinRequestDeleteView.as_view()


class JoinRequestActionView(JoinRequestManageMixin, SuccessMixin, GenericModelView):
    success_url = reverse_lazy("join_requests:list")


class JoinRequestAcceptView(JoinRequestActionView):
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(
                status__in=(JoinRequest.Status.PENDING, JoinRequest.Status.REJECTED)
            )
        )

    def get_success_message(self):
        return _("Join request for %(sender)s has been accepted") % {
            "sender": self.object.sender.get_display_name()
        }

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if Membership.objects.filter(
            member=self.object.sender, community=self.object.community
        ).exists():
            messages.error(request, _("User already belongs to this community"))
            return HttpResponseRedirect(reverse("join_requests:list"))

        self.object.accept()

        Membership.objects.create(
            member=self.object.sender, community=self.object.community
        )

        send_acceptance_email(self.object)

        self.object.sender.notify_on_join(self.object.community)

        return self.success_response()


join_request_accept_view = JoinRequestAcceptView.as_view()


class JoinRequestRejectView(JoinRequestActionView):
    def get_queryset(self):
        return super().get_queryset().pending()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.reject()

        send_rejection_email(self.object)

        messages.info(
            request,
            _("Join request for %(sender)s has been rejected")
            % {"sender": self.object.sender.get_display_name()},
        )

        return self.success_response()


join_request_reject_view = JoinRequestRejectView.as_view()


class JoinRequestCreateView(
    PermissionRequiredMixin, CommunityRequiredMixin, SuccessMixin, CreateView,
):
    model = JoinRequest
    form_class = JoinRequestForm
    template_name = "join_requests/joinrequest_form.html"
    allow_non_members = True
    permission_required = "join_requests.create"
    success_message = _("Your request has been sent to the community admins")

    def get_permission_object(self):
        return self.request.community

    def get_form(self, *args, **kwargs):
        return self.get_form_class()(
            self.request.user, self.request.community, *args, **kwargs
        )

    def get_success_url(self):
        return reverse("community_welcome")

    def form_valid(self, form):

        join_request = form.save()

        send_join_request_email(join_request)

        return self.success_response()


join_request_create_view = JoinRequestCreateView.as_view()


class SentJoinRequestListView(LoginRequiredMixin, ListView):
    """
    List of pending join requests sent by this user
    """

    paginate_by = settings.LOCALHUB_LONG_PAGE_SIZE
    template_name = "join_requests/sent_joinrequest_list.html"

    def get_queryset(self):
        return (
            JoinRequest.objects.pending()
            .for_sender(self.request.user)
            .select_related("community")
            .order_by("-created")
        )


sent_join_request_list_view = SentJoinRequestListView.as_view()

templates/join_requests/base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "communities/base.html" %}
{% load i18n %}

{% block subtitle %} / {% trans "Join Requests" %}{% endblock %}

templates/join_requests/joinrequest_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h5>{% trans "Delete Join Requst" %}</h5>

<form method="POST"
      action="{{ request.path }}">
  {% csrf_token %}
  <p>{% trans "Do you really want to delete this request?" %}</p>
  <a class="btn btn-link"
     href="{{ object.get_absolute_url }}">{% trans "Cancel" %}</a>
  <button class="btn btn-primary"
          type="submit">{% trans "Delete" %}</button>
</form>

{% endblock content %}

templates/join_requests/joinrequest_detail.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "join_requests/base.html" %}

{% load i18n %}
{% load account %}
{% load activities_tags %}
{% load users_tags %}

{% block content %}

{% user_display object.sender as display_name %}

<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{% url 'communities:community_update' %}">{% trans "Site Settings" %}</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'join_requests:list' %}">{% trans "Join Requests" %}</a>
  </li>
  <li class="breadcrumb-item">
    <a data-turbolinks="false"
       href="#">{{ display_name }}</a>
  </li>
</ul>

<h5>
  {% avatar object.sender "avatar-lg" %}
  {% if object.sender.username == display_name %}
  @{{ display_name }}
  {% else %}
  {{ display_name }}
  (@{{ object.sender.username }})
  {% endif %}
</h5>

{% with is_pending=object.is_pending is_rejected=object.is_rejectd %}
<div class="actions mb-1">
  {% if is_pending or is_rejected %}
  <a data-controller="ajax"
     data-action="ajax#post"
     data-ajax-confirm-header="{% trans 'Accept' %}"
     data-ajax-confirm-body="{% trans 'Are you sure you want to accept this request?' %}"
     data-ajax-redirect="{{ request.get_full_path }}"
     href="{% url 'join_requests:accept' object.id %}">{% trans "Accept" %}
  </a>
  {% endif %}
  {% if is_pending %}
  <a data-controller="ajax"
     data-action="ajax#post"
     data-ajax-redirect="{{ request.get_full_path }}"
     data-ajax-confirm-header="{% trans 'Reject' %}"
     data-ajax-confirm-body="{% trans 'Are you sure you want to reject this request?' %}"
     href="{% url 'join_requests:reject' object.id %}">{% trans "Reject" %}</a>
  {% endif %}
  <a data-controller="ajax"
     data-action="ajax#post"
     data-ajax-confirm-header="{% trans 'Delete' %}"
     data-ajax-confirm-body="{% trans 'Are you sure you want to delete this request?' %}"
     href="{% url 'join_requests:delete' object.id %}">{% trans "Delete" %}</a>
</div>
{% endwith %}


<dl>
  <dt>{% trans "Status" %}</dt>
  <dd>{{ object.get_status_display }}</dd>
  <dt>{% trans "Requested" %}</dt>
  <dd>
    {% blocktrans with created=object.created|timesince %}{{ created }} ago{% endblocktrans %}
  </dd>
</dl>

{% if object.sender.bio %}
<h4>{% trans "About this person" %}</h4>
{% collapsable %}
<div class="markdown-content">
  {{ object.sender.bio.markdown|strip_external_images:user }}
</div>
{% endcollapsable %}
{% endif %}


{% if object.intro %}
<h5 class="mt-1">{% trans "Introduction" %}</h5>
{{ object.intro|linebreaks }}
{% endif %}

{% endblock content %}

templates/join_requests/joinrequest_form.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h5>{% trans "Request Invitation" %}</h5>
<p>
  {% trans "Your request will be sent to the site admins. If they approve your request, you will automatically become a member of this community." %}
</p>
{% include "includes/forms/stimulusjs_form.html" %}
{% endblock %}

templates/join_requests/joinrequest_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "join_requests/base.html" %}
{% load i18n %}
{% load account %}

{% block content %}

<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{% url 'communities:community_update' %}">{% trans "Site Settings" %}</a>
  </li>
  <li class="breadcrumb-item">
    <a data-turbolinks="false"
       href="#">{% trans "Join Requests" %}</a>
  </li>
</ul>


<h5>
  {% trans "Join Requests" %}
  {% if status_display %}
  - {{ status_display}}
  {% endif %}
</h5>

{% if paginator.count or view.search_query %}
{% include "includes/forms/search_form.html" with selector=True %}
{% endif %}

{% if not community.allow_join_requests %}
<p class="toast text-center my-2">
  {% url 'communities:community_update' as settings_url %}
  {% blocktrans %}Join requests are currently disabled for this community. You can re-enable them <a
     href="{{ settings_url }}">in your community settings</a>.{% endblocktrans %}
</p>
{% endif %}

{% if total_count %}
<div class="actions my-1">
  {% if status %}
  <a href="{{ request.path }}">{% trans "Show All" %}</a>
  {% endif %}
  {% for value, label in status_choices %}
  {% if status != value %}
  <a href="{{ request.path }}?status={{ value }}">{{ label }}</a>
  {% endif %}
  {% endfor %}
</div>
{% endif %}


{% if object_list %}
<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>{% trans "User" %}</th>
      <th>{% trans "Status" %}</th>
      <th>{% trans "Actions" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for join_request in object_list %}
    {% with is_pending=join_request.is_pending is_rejected=join_request.is_rejected detail_url=join_request.get_absolute_url %}
    <tr>
      <td>
        {% if is_pending %}<b>{% endif %}
          <a href="{{ detail_url }}">{% user_display join_request.sender %}</a>
          {% if is_pending %}</b>{% endif %}
      </td>
      <td>
        {% if is_pending %}<b>{% endif %}
          {{ join_request.get_status_display }}
          {% if is_pending %}</b>{% endif %}
      </td>
      <td>
        <div class="actions">
          {% if is_pending or is_rejected %}
          <a data-controller="ajax"
             data-action="ajax#post"
             data-ajax-confirm-header="{% trans 'Accept' %}"
             data-ajax-confirm-body="{% trans 'Are you sure you want to accept this request?' %}"
             href="{% url 'join_requests:accept' join_request.id %}">{% trans "Accept" %}
          </a>
          {% endif %}
          {% if is_pending %}
          <a data-controller="ajax"
             data-action="ajax#post"
             data-ajax-confirm-header="{% trans 'Reject' %}"
             data-ajax-confirm-body="{% trans 'Are you sure you want to reject this request?' %}"
             href="{% url 'join_requests:reject' join_request.id %}">{% trans "Reject" %}</a>
          {% endif %}

          <a data-controller="ajax"
             data-action="ajax#post"
             data-ajax-confirm-header="{% trans 'Delete' %}"
             data-ajax-confirm-body="{% trans 'Are you sure you want to delete this request?' %}"
             href="{% url 'join_requests:delete' join_request.id %}">{% trans "Delete" %}</a>
        </div>
      </td>
    </tr>
    {% endwith %}
    {% endfor %}
  </tbody>
</table>
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}
{% endblock content %}

templates/join_requests/sent_joinrequest_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "base.html" %}

{% load i18n %}
{% load rules %}

{% block content %}

<h5>{% trans "Join Requests" %}</h5>

{% has_perm "communities.manage_community" user community as can_manage_community %}
{% if can_manage_community %}
<div class="actions">
    <a href="{% url 'join_requests:list' %}">{% trans "Manage join requests" %}</a>
</div>
{% endif %}


{% if object_list %}
<table class="table table-hover table-responsive">
    <thead>
        <tr>
            <th>{% trans "Community" %}</th>
            <th>{% trans "Status" %}</th>
            <th>{% trans "Actions" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for join_request in object_list %}
        <tr>
            <td>
                {{ join_request.community.name }}
            </td>
            <td>
                {{ join_request.get_status_display }}
            </td>
            <td>
                <a href="{% url 'join_requests:delete' join_request.id %}"
                   data-controller="ajax"
                   data-action="ajax#post">
                    {% trans "Delete" %}
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}
{% endblock content %}