localhub/bookmarks/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    bookmarks_comment_list_view,
    bookmarks_message_list_view,
    bookmarks_stream_view,
)

app_name = "bookmarks"

urlpatterns = [
    path("", bookmarks_stream_view, name="activities"),
    path("comments/", bookmarks_comment_list_view, name="comments"),
    path("messages/", bookmarks_message_list_view, name="messages"),
]

localhub/notifications/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    notification_delete_all_view,
    notification_delete_view,
    notification_list_view,
    notification_mark_all_read_view,
    notification_mark_read_view,
    service_worker_view,
    subscribe_view,
    unsubscribe_view,
)

app_name = "notifications"

urlpatterns = [
    path("", notification_list_view, name="list"),
    path("service-worker.js", service_worker_view, name="service_worker"),
    path("~subscribe/", subscribe_view, name="subscribe"),
    path("~unsubscribe/", unsubscribe_view, name="unsubscribe"),
    path("<int:pk>/~delete/", notification_delete_view, name="delete"),
    path("<int:pk>/~mark-read/", notification_mark_read_view, name="mark_read"),
    path("~delete-all/", notification_delete_all_view, name="delete_all"),
    path("~mark-all-read/", notification_mark_all_read_view, name="mark_all_read",),
]

localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path, re_path

from localhub.users.urls import USERNAME_RE

from .views import (
    inbox_view,
    message_bookmark_view,
    message_create_view,
    message_delete_view,
    message_detail_view,
    message_follow_up_view,
    message_mark_all_read_view,
    message_mark_read_view,
    message_remove_bookmark_view,
    message_reply_view,
    outbox_view,
)

app_name = "private_messages"

urlpatterns = [
    path("inbox/", inbox_view, name="inbox"),
    path("outbox/", outbox_view, name="outbox"),
    path("~/mark-read/", message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", message_detail_view, name="message_detail"),
    path(
        "message/<int:pk>/~follow-up/", message_follow_up_view, name="message_follow_up"
    ),
    path("message/<int:pk>/~reply/", message_reply_view, name="message_reply"),
    path("message/<int:pk>/~delete/", message_delete_view, name="message_delete"),
    path("message/<int:pk>/~read/", message_mark_read_view, name="message_mark_read"),
    path(
        "message/<int:pk>/~bookmark/", message_bookmark_view, name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        message_remove_bookmark_view,
        name="message_remove_bookmark",
    ),
    re_path(USERNAME_RE + r"~send/$", message_create_view, name="message_create"),
]

localhub/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from localhub.activities.views.streams import activity_stream_view
from localhub.communities.views import (
    community_list_view,
    community_not_found_view,
    community_sidebar_view,
    community_welcome_view,
)
from localhub.users.views import (
    dismiss_notice_view,
    switch_theme_view,
    user_delete_view,
    user_update_view,
)

urlpatterns = [
    # Local
    path("", view=activity_stream_view, name="activity_stream"),
    path("", include("localhub.activities.urls")),
    path("bookmarks/", include("localhub.bookmarks.urls")),
    path("comments/", include("localhub.comments.urls")),
    path("events/", include("localhub.events.urls")),
    path("flags/", include("localhub.flags.urls")),
    path("invites/", include("localhub.invites.urls")),
    path("join-requests/", include("localhub.join_requests.urls")),
    path("notifications/", include("localhub.notifications.urls")),
    path("favorites/", include("localhub.likes.urls")),
    path("messages/", include("localhub.private_messages.urls")),
    path("photos/", include("localhub.photos.urls")),
    path("polls/", include("localhub.polls.urls")),
    path("posts/", include("localhub.posts.urls")),
    path("people/", include("localhub.users.urls")),
    path("site/", include("localhub.communities.urls")),
    path("sites/", community_list_view, name="community_list"),
    path("account/~update", user_update_view, name="user_update"),
    path("account/~delete", user_delete_view, name="user_delete"),
    path("welcome/", view=community_welcome_view, name="community_welcome"),
    path("sidebar/", view=community_sidebar_view, name="community_sidebar"),
    path("not-found/", view=community_not_found_view, name="community_not_found"),
    path("~theme/<str:theme>/", switch_theme_view, name="switch_theme"),
    path("~dismiss-notice/<str:notice>/", dismiss_notice_view, name="dismiss_notice"),
    # Third-party
    path("account/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

# silk
if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:

    # debug toolbar
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # static views
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # allow preview/debugging of error views in development
    urlpatterns += [
        path("errors/400/", TemplateView.as_view(template_name="400.html")),
        path("errors/403/", TemplateView.as_view(template_name="403.html")),
        path("errors/404/", TemplateView.as_view(template_name="404.html")),
        path("errors/405/", TemplateView.as_view(template_name="405.html")),
        path("errors/500/", TemplateView.as_view(template_name="500.html")),
        path("errors/csrf/", TemplateView.as_view(template_name="403_csrf.html")),
    ]

localhub/private_messages/forms.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("message",)
        labels = {"message": _("Send Message")}

localhub/bookmarks/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from vanilla import ListView

from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.views import BaseCommentListView
from localhub.private_messages.views import SenderOrRecipientQuerySetMixin


class BookmarksStreamView(BaseActivityStreamView):
    template_name = "bookmarks/activities.html"
    ordering = ("-bookmarked", "-created")

    def get_count_queryset_for_model(self, model):
        return self.filter_queryset(
            model.objects.published_or_owner(self.request.user).bookmarked(
                self.request.user
            )
        )

    def filter_queryset(self, queryset):
        return (
            super()
            .filter_queryset(queryset)
            .published_or_owner(self.request.user)
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
        )


bookmarks_stream_view = BookmarksStreamView.as_view()


class BookmarksCommentListView(BaseCommentListView):
    template_name = "bookmarks/comments.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_common_annotations(self.request.user, self.request.community)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )


bookmarks_comment_list_view = BookmarksCommentListView.as_view()


class BookmarksMessageListView(SenderOrRecipientQuerySetMixin, ListView):

    template_name = "bookmarks/messages.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )


bookmarks_message_list_view = BookmarksMessageListView.as_view()

localhub/notifications/views/notifications.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from vanilla import DeleteView, GenericModelView, ListView

from localhub.communities.views import CommunityRequiredMixin
from localhub.views import SuccessMixin

from ..models import Notification
from ..signals import notification_read


class NotificationQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return Notification.objects.for_community(self.request.community).for_recipient(
            self.request.user
        )


class UnreadNotificationQuerySetMixin(NotificationQuerySetMixin):
    def get_queryset(self):
        return super().get_queryset().unread()


class NotificationSuccessMixin(SuccessMixin):
    success_url = reverse_lazy("notifications:list")


class NotificationListView(NotificationQuerySetMixin, ListView):
    paginate_by = settings.LOCALHUB_LONG_PAGE_SIZE
    template_name = "notifications/notification_list.html"
    model = Notification

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .exclude_blocked_actors(self.request.user)
            .prefetch_related("content_object")
            .select_related("actor", "content_type", "community", "recipient")
            .order_by("is_read", "-created")
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["is_unread_notifications"] = (
            self.get_queryset().filter(is_read=False).exists()
        )
        return data


notification_list_view = NotificationListView.as_view()


class NotificationMarkAllReadView(
    UnreadNotificationQuerySetMixin, NotificationSuccessMixin, GenericModelView,
):
    def post(self, request, *args, **kwargs):
        qs = self.get_queryset()
        [
            notification_read.send(
                sender=notification.content_object.__class__,
                instance=notification.content_object,
            )
            for notification in qs.prefetch_related("content_object")
        ]
        qs.update(is_read=True)
        return HttpResponseRedirect(self.get_success_url())


notification_mark_all_read_view = NotificationMarkAllReadView.as_view()


class NotificationMarkReadView(
    UnreadNotificationQuerySetMixin, NotificationSuccessMixin, GenericModelView,
):
    def post(self, request, *args, **kwargs):
        notification = self.get_object()
        notification.is_read = True
        notification.save()

        notification_read.send(
            sender=notification.content_object.__class__,
            instance=notification.content_object,
        )

        return HttpResponseRedirect(self.get_success_url())


notification_mark_read_view = NotificationMarkReadView.as_view()


class NotificationDeleteAllView(
    NotificationQuerySetMixin, NotificationSuccessMixin, GenericModelView,
):
    def delete(self, request):
        self.get_queryset().delete()
        return HttpResponseRedirect(self.get_success_url())

    def post(self, request):
        return self.delete(request)


notification_delete_all_view = NotificationDeleteAllView.as_view()


class NotificationDeleteView(
    NotificationQuerySetMixin, NotificationSuccessMixin, DeleteView
):

    ...


notification_delete_view = NotificationDeleteView.as_view()

localhub/notifications/views/webpush.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

import json

from django.conf import settings
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.generic import View
from vanilla import TemplateView

from localhub.communities.views import CommunityRequiredMixin

from ..models import PushSubscription


class BasePushSubscriptionView(CommunityRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            json_body = json.loads(request.body.decode("utf-8"))

            data = {"endpoint": json_body["endpoint"]}
            keys = json_body["keys"]
            data["auth"] = keys["auth"]
            data["p256dh"] = keys["p256dh"]

        except (ValueError, KeyError):
            return HttpResponseBadRequest()

        return self.handle_action(request, **data)

    def handle_action(self, request, auth, p256dh, endpoint):
        raise NotImplementedError


class ServiceWorkerView(TemplateView):
    """
    Returns template containing serviceWorker JS, can't use
    static as must always be under domain. We can also pass
    in server specific settings.
    """

    template_name = "notifications/service_worker.js"

    def get(self, request):
        response = super().get(request)
        response["Content-Type"] = "application/javascript"
        return response

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["vapid_public_key"] = settings.VAPID_PUBLIC_KEY
        return data


service_worker_view = ServiceWorkerView.as_view()


class SubscribeView(BasePushSubscriptionView):
    def handle_action(self, request, auth, p256dh, endpoint):

        try:
            PushSubscription.objects.get_or_create(
                auth=auth,
                p256dh=p256dh,
                endpoint=endpoint,
                user=request.user,
                community=request.community,
            )
        except IntegrityError:
            pass  # dupe, ignore

        return JsonResponse({"message": "ok"}, status=201)


subscribe_view = SubscribeView.as_view()


class UnsubscribeView(BasePushSubscriptionView):
    def handle_action(self, request, auth, p256dh, endpoint):

        PushSubscription.objects.filter(
            auth=auth,
            p256dh=p256dh,
            endpoint=endpoint,
            user=request.user,
            community=request.community,
        ).delete()

        return JsonResponse({"message": "ok"}, status=200)


unsubscribe_view = UnsubscribeView.as_view()

templates/private_messages/includes/bookmark.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if has_bookmarked %}
<a href="{% url 'private_messages:message_remove_bookmark' message.id %}"
   data-action="ajax#post"><s>{% trans "Bookmark" %}</s></a>
{% else %}
<a href="{% url 'private_messages:message_bookmark' message.id %}"
   data-action="ajax#post">{% trans "Bookmark" %}</a>
{% endif %}

templates/private_messages/includes/email_settings.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load users_tags %}

{% dismissable user "messages-emails" %}
{% url 'user_update' as user_settings_url %}
{% blocktrans %}
You can enable email notifications for new messages <a href="{{ user_settings_url }}">in your settings</a>.
{% endblocktrans %}
{% enddismissable %}

templates/private_messages/includes/message.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load activities_tags %}

<div class="card mb-2{% if is_sender %} bg-gray{% endif %} message"
     id="message-{{ message.id }}"
     data-controller="clipboard">
  <div class="card-header">
    <div class="card-subtitle h6 {% if is_unread %}text-bold{% endif %}">
      {% include "users/includes/chip.html" with profile=message.sender profile_url=sender_url %}
      <span class="timesince">
        {% trans "to" %}
      </span>
      {% include "users/includes/chip.html" with profile=message.recipient profile_url=recipient_url %}
      <span class="timesince">
        {% blocktrans with created=message.created|timesince %}
        {{ created }} ago
        {% endblocktrans %}
      </span>
      {% if is_unread %}
      <div class="label bg-primary">{% trans "New" %}</div>
      {% endif %}
    </div>
  </div>
  <div class="card-body">
    {% collapsable is_detail %}
    <div class="markdown-content mt-1">
      {{ message.message.markdown|strip_external_images:user }}
    </div>
    {% endcollapsable %}
    <textarea data-target="clipboard.textarea"
              readonly
              class="d-none">{{ message.message }}</textarea>
  </div>
  <div class="card-footer">
    <div class="d-flex align-center mt-1">
      <div class="dropdown mr-2"
           data-controller="toggle">
        <a class="btn btn-sm dropdown-toggle"
           tabindex="0">
          {% trans "Actions" %}<i class="icon icon-caret"></i>
        </a>
        <ul class="menu">
          {% if is_recipient and not message.read %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_mark_read' message.id %}"
               data-controller="ajax"
               data-action="ajax#post"
               data-ajax-redirect="{{ request.get_full_path }}">{% trans "Mark As Read" %}</a>
          </li>
          {% endif %}

          <li class="menu-item"
              data-controller="ajax"
              data-ajax-replace>
            {% include "private_messages/includes/bookmark.html" with has_bookmarked=message.has_bookmarked %}
          </li>

          {% if can_reply %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_reply' message.id %}">
              {% trans "Reply" %}
            </a>
          </li>
          {% elif can_follow_up %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_follow_up' message.id %}">
              {% trans "Follow-Up" %}
            </a>
          </li>
          {% endif %}
          <li class="menu-item">
            <a href="{% url 'private_messages:message_delete' message.id %}"
               data-controller="ajax"
               data-action="ajax#post"
               data-ajax-redirect="{{ post_delete_redirect|default:request.get_full_path }}"
               data-ajax-confirm-header="{% trans 'Delete Message' %}"
               data-ajax-confirm-body="{% trans "Are you sure you want to delete this message? Replies to this message will not be deleted. The message may still be available to the other person." %}">{% trans "Delete" %}</a>

          </li>
          <li class="menu-item">
            <a href="#"
               data-target="clipboard.button"
               data-action="clipboard#copy">
              {% trans "Copy Markdown" %}
            </a>
          </li>
        </ul>
      </div>
      {% if not is_detail %}
      <div class="actions">
        <a href="{{ message_url }}">{% trans "Link" %}</a>
        {% if parent %}
        <a href="{{ parent_url }}">{% trans "Parent" %}</a>
        {% endif %}
      </div>
      {% endif %}
    </div>
    <div class="clearfix"></div>
  </div>
</div>

templates/private_messages/includes/message_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load private_messages_tags %}

{% if object_list %}
{% for message in object_list %}
{% render_message request user message %}
{% endfor %}
{% include "includes/pagination.html" %}
{% else %}
{% include "includes/empty.html" %}
{% endif %}

templates/private_messages/includes/notification.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% if verb == "reply" %}
{% blocktrans %}
<a href="{{ actor_url }}">{{ actor_display }}</a> has replied to your <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% elif verb == "follow_up" %}
{% blocktrans %}
<a href="{{ actor_url }}">{{ actor_display }}</a> has sent you a <a href="{{ object_url }}">follow-up</a> to one of
their messages.
{% endblocktrans %}
{% else %}
{% blocktrans %}
<a href="{{ actor_url }}">{{ actor_display }}</a> has sent you a <a href="{{ object_url }}">message</a>.
{% endblocktrans %}
{% endif %}