localhub/bookmarks/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    bookmarks_comment_list_view,
    bookmarks_message_list_view,
    bookmarks_stream_view,
)

app_name = "bookmarks"

urlpatterns = [
    path("", bookmarks_stream_view, name="activities"),
    path("comments/", bookmarks_comment_list_view, name="comments"),
    path("messages/", bookmarks_message_list_view, name="messages"),
]

localhub/comments/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import (
    comment_bookmark_view,
    comment_delete_view,
    comment_detail_view,
    comment_dislike_view,
    comment_flag_view,
    comment_like_view,
    comment_list_view,
    comment_remove_bookmark_view,
    comment_reply_view,
    comment_update_view,
)

app_name = "comments"


urlpatterns = [
    path("", comment_list_view, name="list"),
    path("<int:pk>/", comment_detail_view, name="detail"),
    path("<int:pk>/~update/", comment_update_view, name="update"),
    path("<int:pk>/~delete/", comment_delete_view, name="delete"),
    path("<int:pk>/~like/", comment_like_view, name="like"),
    path("<int:pk>/~bookmark/", comment_bookmark_view, name="bookmark"),
    path(
        "<int:pk>/~bookmark/remove/",
        comment_remove_bookmark_view,
        name="remove_bookmark",
    ),
    path("<int:pk>/~dislike/", comment_dislike_view, name="dislike"),
    path("<int:pk>/~flag/", comment_flag_view, name="flag"),
    path("<int:pk>/~reply/", comment_reply_view, name="reply"),
]

localhub/likes/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import liked_comment_list_view, liked_stream_view

app_name = "likes"

urlpatterns = [
    path("", liked_stream_view, name="activities"),
    path("comments/", liked_comment_list_view, name="comments"),
]

localhub/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from localhub.activities.views.streams import activity_stream_view
from localhub.communities.views import (
    community_list_view,
    community_not_found_view,
    community_sidebar_view,
    community_welcome_view,
)
from localhub.users.views import (
    dismiss_notice_view,
    switch_theme_view,
    user_delete_view,
    user_update_view,
)

urlpatterns = [
    # Local
    path("", view=activity_stream_view, name="activity_stream"),
    path("", include("localhub.activities.urls")),
    path("bookmarks/", include("localhub.bookmarks.urls")),
    path("comments/", include("localhub.comments.urls")),
    path("events/", include("localhub.events.urls")),
    path("flags/", include("localhub.flags.urls")),
    path("invites/", include("localhub.invites.urls")),
    path("join-requests/", include("localhub.join_requests.urls")),
    path("notifications/", include("localhub.notifications.urls")),
    path("favorites/", include("localhub.likes.urls")),
    path("messages/", include("localhub.private_messages.urls")),
    path("photos/", include("localhub.photos.urls")),
    path("polls/", include("localhub.polls.urls")),
    path("posts/", include("localhub.posts.urls")),
    path("people/", include("localhub.users.urls")),
    path("site/", include("localhub.communities.urls")),
    path("sites/", community_list_view, name="community_list"),
    path("account/~update", user_update_view, name="user_update"),
    path("account/~delete", user_delete_view, name="user_delete"),
    path("welcome/", view=community_welcome_view, name="community_welcome"),
    path("sidebar/", view=community_sidebar_view, name="community_sidebar"),
    path("not-found/", view=community_not_found_view, name="community_not_found"),
    path("~theme/<str:theme>/", switch_theme_view, name="switch_theme"),
    path("~dismiss-notice/<str:notice>/", dismiss_notice_view, name="dismiss_notice"),
    # Third-party
    path("account/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

# silk
if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:

    # debug toolbar
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # static views
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # allow preview/debugging of error views in development
    urlpatterns += [
        path("errors/400/", TemplateView.as_view(template_name="400.html")),
        path("errors/403/", TemplateView.as_view(template_name="403.html")),
        path("errors/404/", TemplateView.as_view(template_name="404.html")),
        path("errors/405/", TemplateView.as_view(template_name="405.html")),
        path("errors/500/", TemplateView.as_view(template_name="500.html")),
        path("errors/csrf/", TemplateView.as_view(template_name="403_csrf.html")),
    ]

localhub/users/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path, re_path

from .views import (
    blocked_user_list_view,
    follower_user_list_view,
    following_user_list_view,
    member_list_view,
    user_autocomplete_list_view,
    user_block_view,
    user_comment_list_view,
    user_follow_view,
    user_message_list_view,
    user_stream_view,
    user_unblock_view,
    user_unfollow_view,
)

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"

urlpatterns = [
    path("autocomplete/", view=user_autocomplete_list_view, name="autocomplete_list",),
    path("members/", view=member_list_view, name="member_list"),
    path("following/", view=following_user_list_view, name="following_list"),
    path("followers/", view=follower_user_list_view, name="follower_list"),
    path("blocked/", view=blocked_user_list_view, name="blocked_list"),
    re_path(USERNAME_RE + r"follow/$", view=user_follow_view, name="follow"),
    re_path(USERNAME_RE + r"unfollow/$", view=user_unfollow_view, name="unfollow"),
    re_path(USERNAME_RE + r"block/$", view=user_block_view, name="block"),
    re_path(USERNAME_RE + r"unblock/$", view=user_unblock_view, name="unblock"),
    re_path(USERNAME_RE + r"comments/$", view=user_comment_list_view, name="comments"),
    re_path(USERNAME_RE + r"messages/$", view=user_message_list_view, name="messages"),
    re_path(USERNAME_RE + r"$", view=user_stream_view, name="activities"),
]

localhub/bookmarks/models.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from model_utils.models import TimeStampedModel

from localhub.communities.models import Community
from localhub.db.content_types import (
    get_generic_related_exists,
    get_generic_related_value_subquery,
)


class BookmarkAnnotationsQuerySetMixin:
    """
    Annotation methods for related model query sets.
    """

    def with_has_bookmarked(self, user, annotated_name="has_bookmarked"):
        """Checks if user has liked the objects, adding `has_liked`
        annotation.

        Args:

            user (User): user who has bookmarked the items
            annotated_name (str, optional): annotation name (default: "has_bookmarked")

        Returns:

            QuerySet
        """
        return self.annotate(
            **{
                annotated_name: get_generic_related_exists(
                    self.model, Bookmark.objects.filter(user=user)
                )
            }
        )

    def bookmarked(self, user, annotated_name="has_bookmarked"):
        """Filters queryset and returns only those which have been bookmarked.

        Args:

            user (User): user who has bookmarked the items
            annotated_name (str, optional): annotation name (default: "has_bookmarked")

        Returns:

            QuerySet
        """
        return self.with_has_bookmarked(user, annotated_name).filter(
            **{annotated_name: True}
        )

    def with_bookmarked_timestamp(self, user, annotated_name="bookmarked"):
        """Adds annotated "bookmarked" timestamp to bookmarked items.

        Args:
            user (User): user who has bookmarked the items
            annotated_name (str, optional): annotation timestamp name (default: "bookmarked")

        Returns:
            QuerySet
        """

        return self.annotate(
            **{
                annotated_name: get_generic_related_value_subquery(
                    self.model,
                    Bookmark.objects.filter(user=user),
                    "created",
                    models.DateTimeField(),
                )
            }
        )


class BookmarkQuerySet(models.QuerySet):
    def for_models(self, *models):
        """
        Returns instances of a Bookmark for a given set of models.
        """
        return self.filter(
            content_type__in=ContentType.objects.get_for_models(*models).values()
        )


class Bookmark(TimeStampedModel):

    community = models.ForeignKey(Community, related_name="+", on_delete=models.CASCADE)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="+", on_delete=models.CASCADE
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    objects = BookmarkQuerySet.as_manager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "content_type", "object_id"], name="unique_bookmark",
            )
        ]
        indexes = [models.Index(fields=["content_type", "object_id"])]

localhub/likes/models.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from model_utils.models import TimeStampedModel

from localhub.communities.models import Community
from localhub.db.content_types import (
    get_generic_related_count_subquery,
    get_generic_related_exists,
    get_generic_related_value_subquery,
)
from localhub.notifications.decorators import dispatch
from localhub.notifications.models import Notification


class LikeAnnotationsQuerySetMixin:
    """
    Annotation methods for related model query sets.
    """

    def with_num_likes(self, annotated_name="num_likes"):
        """Appends the total number of likes each object has received.

        Args:
            annotated_name (str, optional): the annotation name (default: "num_likes")
        """
        return self.annotate(
            **{annotated_name: get_generic_related_count_subquery(self.model, Like)}
        )

    def with_has_liked(self, user, annotated_name="has_liked"):
        """Checks if user has liked the object, adding `has_liked`
        annotation.

        Args:
            user (User): user who has liked the items
            annotated_name (str, optional): the annotation name (default: "has_liked")

        Returns:
            QuerySet
        """
        return self.annotate(
            **{
                annotated_name: get_generic_related_exists(
                    self.model, Like.objects.filter(user=user)
                )
            }
        )

    def liked(self, user, annotated_name="has_liked"):
        """Filters queryset to include only liked items.

        Args:
            user (User): user who has liked the items
            annotated_name (str, optional): the annotation name (default: "has_liked")

        Returns:
            QuerySet
        """
        return self.with_has_liked(user, annotated_name).filter(
            **{annotated_name: True}
        )

    def with_liked_timestamp(self, user, annotated_name="liked"):
        """Filters all items liked by this user and includes annotated
        "liked" timestamp.

        Args:
            user (User)
            annotated_name (str, optional): the annotation name (default: "liked")

        Returns:
            QuerySet
        """
        return self.annotate(
            **{
                annotated_name: get_generic_related_value_subquery(
                    self.model,
                    Like.objects.filter(user=user),
                    "created",
                    models.DateTimeField(),
                )
            }
        )


class LikeQuerySet(models.QuerySet):
    def for_models(self, *models):
        """
        Returns instances of a Like for a given set of models.
        """
        return self.filter(
            content_type__in=ContentType.objects.get_for_models(*models).values()
        )


class Like(TimeStampedModel):

    community = models.ForeignKey(Community, related_name="+", on_delete=models.CASCADE)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="+", on_delete=models.CASCADE
    )

    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="+", on_delete=models.CASCADE
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    objects = LikeQuerySet.as_manager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "content_type", "object_id"], name="unique_like",
            )
        ]
        indexes = [models.Index(fields=["content_type", "object_id"])]

    @dispatch
    def notify(self):
        return Notification(
            content_object=self.content_object,
            recipient=self.recipient,
            actor=self.user,
            community=self.community,
            verb="like",
        )

localhub/comments/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        labels = {"content": _("Comment")}

localhub/bookmarks/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from vanilla import ListView

from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.views import BaseCommentListView
from localhub.private_messages.views import SenderOrRecipientQuerySetMixin


class BookmarksStreamView(BaseActivityStreamView):
    template_name = "bookmarks/activities.html"
    ordering = ("-bookmarked", "-created")

    def get_count_queryset_for_model(self, model):
        return self.filter_queryset(
            model.objects.published_or_owner(self.request.user).bookmarked(
                self.request.user
            )
        )

    def filter_queryset(self, queryset):
        return (
            super()
            .filter_queryset(queryset)
            .published_or_owner(self.request.user)
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
        )


bookmarks_stream_view = BookmarksStreamView.as_view()


class BookmarksCommentListView(BaseCommentListView):
    template_name = "bookmarks/comments.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_common_annotations(self.request.user, self.request.community)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )


bookmarks_comment_list_view = BookmarksCommentListView.as_view()


class BookmarksMessageListView(SenderOrRecipientQuerySetMixin, ListView):

    template_name = "bookmarks/messages.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .bookmarked(self.request.user)
            .with_bookmarked_timestamp(self.request.user)
            .order_by("-bookmarked", "-created")
        )


bookmarks_message_list_view = BookmarksMessageListView.as_view()

localhub/likes/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from localhub.activities.views.streams import BaseActivityStreamView
from localhub.comments.views import BaseCommentListView


class LikedStreamView(BaseActivityStreamView):
    template_name = "likes/activities.html"
    ordering = ("-liked", "-created")

    def get_count_queryset_for_model(self, model):
        return self.filter_queryset(model.objects.liked(self.request.user))

    def filter_queryset(self, queryset):
        return (
            super()
            .filter_queryset(queryset)
            .liked(self.request.user)
            .with_liked_timestamp(self.request.user)
        )


liked_stream_view = LikedStreamView.as_view()


class LikedCommentListView(BaseCommentListView):
    template_name = "likes/comments.html"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .liked(self.request.user)
            .with_common_annotations(self.request.user, self.request.community)
            .with_liked_timestamp(self.request.user)
            .order_by("-liked", "-created")
        )


liked_comment_list_view = LikedCommentListView.as_view()

templates/comments/includes/bookmark.html
    {# Copyright (c) 2020 by Dan Jacob #}
    {# SPDX-License-Identifier: AGPL-3.0-or-later #}

    {% load i18n %}

    {% if has_bookmarked %}
    <a href="{% url 'comments:remove_bookmark' comment.id %}"
       data-action="ajax#post"><s>{% trans "Bookmark" %}</s></a>
    {% else %}
    <a href="{% url 'comments:bookmark' comment.id %}"
       data-action="ajax#post">{% trans "Bookmark" %}</a>
    {% endif %}

templates/comments/includes/comment.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}
{% load account %}
{% load rules %}
{% load activities_tags %}

<article class="card {% if css_class %} {{ css_class }}{% endif %}"
         role="comment"
         data-controller="clipboard"
         id="comment-{{ comment.id }}">
  <div class="card-header">
    {% if include_content_object %}
    <div class="card-title h6">
      {% if content_object %}
      <a href="{{ content_object.get_absolute_url }}">{{ content_object }}</a>
      {% else %}
      {% trans "[Deleted]" %}
      {% endif %}
    </div>
    {% endif %}
    {% has_perm "communities.moderate_community" user community as can_moderate_community %}
    {% if comment.is_flagged and can_moderate_community %}
    <div class="toast toast-info text-center mb-2">
      <a href="{{ comment.get_absolute_url }}">{% trans "This comment has been flagged" %}</a>
    </div>
    {% endif %}

    <div class="card-title h6">
      {% url 'users:comments' comment.owner.username as owner_url %}
      {% include "activities/includes/timesince.html" with profile_url=owner_url timestamp=comment.created owner=comment.owner %}
    </div>
  </div>
  {% if comment.is_blocked %}
  <div class="card-body"
       data-controller="toggle">
    <strong>{% trans "You have blocked this user." %}</strong>
    <div class="markdown-content d-hide"
         data-target="toggle.togglable">
      {{ comment.content.markdown|strip_external_images:user }}
    </div>
    <div class="actions">
      <a href="#"
         data-target="toggle.togglable"
         data-action="toggle#toggle">{% trans "View Comment" %}</a>
    </div>
  </div>
  {% else %}
  <div class="card-body">
    <textarea data-target="clipboard.textarea"
              readonly
              class="d-none">{{ comment.content }}</textarea>
    {% if comment.deleted %}
    <p>{% blocktrans %}This comment has been deleted by a community moderator{% endblocktrans %}</p>
    {% endif %}
    {% if show_content %}
    {% collapsable is_detail %}
    <div class="markdown-content mt-1">
      {{ comment.content.markdown|strip_external_images:user }}
    </div>
    {% endcollapsable %}
    {% endif %}
  </div>
  <div class="card-footer">
    {% if comment.num_likes and comment.owner == user %}
    <div class="info">
      {{ comment.num_likes }}
      {% blocktrans count counter=comment.num_likes %}
      Like
      {% plural %}
      Likes
      {% endblocktrans %}
    </div>
    {% endif %}

    {% if comment.edited %}
    <div class="info">
      {% blocktrans with edited=comment.edited|timesince %}Updated {{ edited }} ago{% endblocktrans %}
    </div>
    {% endif %}
    <div class="d-flex align-center mt-1">
      <div class="dropdown mr-2">
        <a class="btn btn-sm dropdown-toggle"
           tabindex="0">
          {% trans "Actions" %}<i class="icon icon-caret"></i>
        </a>
        <ul class="menu">
          {% has_perm "comments.like_comment" user comment as can_like_comment %}
          {% if can_like_comment %}
          <li class="menu-item"
              data-controller="ajax"
              data-ajax-replace>
            {% include "comments/includes/like.html" with has_liked=comment.has_liked %}
          </li>
          {% endif %}

          {% has_perm "comments.bookmark_comment" user comment as can_bookmark_comment %}
          {% if can_bookmark_comment %}
          <li class="menu-item"
              data-controller="ajax"
              data-ajax-replace>
            {% include "comments/includes/bookmark.html" with has_bookmarked=comment.has_bookmarked %}
          </li>
          {% endif %}

          {% has_perm "comments.reply_to_comment" user comment as can_reply %}
          {% if can_reply %}
          <li class="menu-item">
            <a href="{% url 'comments:reply' comment.id %}">{% trans "Reply" %}</a>
          </li>
          {% endif %}

          {% has_perm "comments.flag_comment" user comment as can_flag_comment %}
          {% if can_flag_comment and not comment.has_flagged %}
          <li class="menu-item">
            <a href="{% url 'comments:flag' comment.id %}">
              {% trans "Flag" %}
            </a>
          </li>
          {% endif %}
          {% has_perm "comments.change_comment" user comment as can_change_comment %}

          {% if can_change_comment %}
          <li class="menu-item">
            <a href="{% url 'comments:update' comment.id %}">
              {% trans "Edit" %}
            </a>
          </li>
          {% endif %}
          {% has_perm "comments.delete_comment" user comment as can_delete_comment %}
          {% if can_delete_comment %}
          <li class="menu-item">
            <a href="{% url 'comments:delete' comment.id %}"
               data-controller="ajax"
               data-action="ajax#post"
               {% if not is_detail %}
               data-ajax-redirect="{{ request.get_full_path }}"
               {% endif %}
               data-ajax-confirm-header="{% trans 'Delete Comment' %}"
               data-ajax-confirm-body="{% trans 'Are you sure you want to delete this comment?' %}">
              {% trans "Delete" %}
            </a>
          </li>
          {% endif %}
          {% if not comment.is_blocked %}
          <li class="menu-item">
            <a href="#"
               data-target="clipboard.button"
               data-action="clipboard#copy">
              {% trans "Copy Markdown" %}
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
      <div class="actions">
        {% if not is_detail and not comment.deleted %}
        <a href="{{ comment.get_absolute_url }}">{% trans "Link" %}</a>
        {% endif %}
        {% if parent %}
        <a href="{{ parent.get_absolute_url }}">{% trans "Parent" %}</a>
        {% endif %}
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
  {% endif %}
</article>

templates/comments/includes/comment_list.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load comments_tags %}

{% for comment in object_list %}
<div class="activity-list-item">
  {% render_comment request user comment include_content_object=True %}
</div>
{% empty %}
{% include "includes/empty.html" %}
{% endfor %}
{% include "includes/pagination.html" %}

templates/comments/includes/like.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% load i18n %}

{% if has_liked %}
<a href="{% url 'comments:dislike' comment.id %}"
   data-action="ajax#post"><s>{% trans "Like" %}</s></a>
{% else %}
<a href="{% url 'comments:like' comment.id %}"
   data-action="ajax#post">{% trans "Like" %}</a>
{% endif %}