localhub/private_messages/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path, re_path

from localhub.users.urls import USERNAME_RE

from .views import (
    inbox_view,
    message_bookmark_view,
    message_create_view,
    message_delete_view,
    message_detail_view,
    message_follow_up_view,
    message_mark_all_read_view,
    message_mark_read_view,
    message_remove_bookmark_view,
    message_reply_view,
    outbox_view,
)

app_name = "private_messages"

urlpatterns = [
    path("inbox/", inbox_view, name="inbox"),
    path("outbox/", outbox_view, name="outbox"),
    path("~/mark-read/", message_mark_all_read_view, name="mark_all_read"),
    path("message/<int:pk>/", message_detail_view, name="message_detail"),
    path(
        "message/<int:pk>/~follow-up/", message_follow_up_view, name="message_follow_up"
    ),
    path("message/<int:pk>/~reply/", message_reply_view, name="message_reply"),
    path("message/<int:pk>/~delete/", message_delete_view, name="message_delete"),
    path("message/<int:pk>/~read/", message_mark_read_view, name="message_mark_read"),
    path(
        "message/<int:pk>/~bookmark/", message_bookmark_view, name="message_bookmark",
    ),
    path(
        "message/<int:pk>/~bookmark/remove/",
        message_remove_bookmark_view,
        name="message_remove_bookmark",
    ),
    re_path(USERNAME_RE + r"~send/$", message_create_view, name="message_create"),
]

localhub/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from localhub.activities.views.streams import activity_stream_view
from localhub.communities.views import (
    community_list_view,
    community_not_found_view,
    community_sidebar_view,
    community_welcome_view,
)
from localhub.users.views import (
    dismiss_notice_view,
    switch_theme_view,
    user_delete_view,
    user_update_view,
)

urlpatterns = [
    # Local
    path("", view=activity_stream_view, name="activity_stream"),
    path("", include("localhub.activities.urls")),
    path("bookmarks/", include("localhub.bookmarks.urls")),
    path("comments/", include("localhub.comments.urls")),
    path("events/", include("localhub.events.urls")),
    path("flags/", include("localhub.flags.urls")),
    path("invites/", include("localhub.invites.urls")),
    path("join-requests/", include("localhub.join_requests.urls")),
    path("notifications/", include("localhub.notifications.urls")),
    path("favorites/", include("localhub.likes.urls")),
    path("messages/", include("localhub.private_messages.urls")),
    path("photos/", include("localhub.photos.urls")),
    path("polls/", include("localhub.polls.urls")),
    path("posts/", include("localhub.posts.urls")),
    path("people/", include("localhub.users.urls")),
    path("site/", include("localhub.communities.urls")),
    path("sites/", community_list_view, name="community_list"),
    path("account/~update", user_update_view, name="user_update"),
    path("account/~delete", user_delete_view, name="user_delete"),
    path("welcome/", view=community_welcome_view, name="community_welcome"),
    path("sidebar/", view=community_sidebar_view, name="community_sidebar"),
    path("not-found/", view=community_not_found_view, name="community_not_found"),
    path("~theme/<str:theme>/", switch_theme_view, name="switch_theme"),
    path("~dismiss-notice/<str:notice>/", dismiss_notice_view, name="dismiss_notice"),
    # Third-party
    path("account/", include("allauth.urls")),
    path("markdownx/", include("markdownx.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
]

# silk
if "silk" in settings.INSTALLED_APPS:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:

    # debug toolbar
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # static views
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # allow preview/debugging of error views in development
    urlpatterns += [
        path("errors/400/", TemplateView.as_view(template_name="400.html")),
        path("errors/403/", TemplateView.as_view(template_name="403.html")),
        path("errors/404/", TemplateView.as_view(template_name="404.html")),
        path("errors/405/", TemplateView.as_view(template_name="405.html")),
        path("errors/500/", TemplateView.as_view(template_name="500.html")),
        path("errors/csrf/", TemplateView.as_view(template_name="403_csrf.html")),
    ]

localhub/users/urls.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path, re_path

from .views import (
    blocked_user_list_view,
    follower_user_list_view,
    following_user_list_view,
    member_list_view,
    user_autocomplete_list_view,
    user_block_view,
    user_comment_list_view,
    user_follow_view,
    user_message_list_view,
    user_stream_view,
    user_unblock_view,
    user_unfollow_view,
)

app_name = "users"

USERNAME_RE = r"^(?P<username>[\w.@+-]+)/"

urlpatterns = [
    path("autocomplete/", view=user_autocomplete_list_view, name="autocomplete_list",),
    path("members/", view=member_list_view, name="member_list"),
    path("following/", view=following_user_list_view, name="following_list"),
    path("followers/", view=follower_user_list_view, name="follower_list"),
    path("blocked/", view=blocked_user_list_view, name="blocked_list"),
    re_path(USERNAME_RE + r"follow/$", view=user_follow_view, name="follow"),
    re_path(USERNAME_RE + r"unfollow/$", view=user_unfollow_view, name="unfollow"),
    re_path(USERNAME_RE + r"block/$", view=user_block_view, name="block"),
    re_path(USERNAME_RE + r"unblock/$", view=user_unblock_view, name="unblock"),
    re_path(USERNAME_RE + r"comments/$", view=user_comment_list_view, name="comments"),
    re_path(USERNAME_RE + r"messages/$", view=user_message_list_view, name="messages"),
    re_path(USERNAME_RE + r"$", view=user_stream_view, name="activities"),
]

localhub/communities/views/base.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class CommunityRequiredMixin(LoginRequiredMixin):
    """
    Ensures that a community is available on this domain. This requires
    the CurrentCommunityMiddleware is enabled.

    If the user is not a member they will be redirected to the Welcome view.

    If the view has the `allow_non_members` property *True* then the above
    rule is overriden - for example in some cases where we want to allow
    the user to be able to handle an invitation.
    """

    allow_non_members = False

    def dispatch(self, request, *args, **kwargs):
        if not request.community.active:
            return self.handle_community_not_found()

        if (
            request.user.is_authenticated
            and not request.user.has_perm(
                "communities.view_community", request.community
            )
            and not self.allow_non_members
        ):
            return self.handle_community_access_denied()
        return super().dispatch(request, *args, **kwargs)

    def handle_community_access_denied(self):
        if self.request.is_ajax():
            raise PermissionDenied(_("You must be a member of this community"))
        return HttpResponseRedirect(reverse("community_welcome"))

    def handle_community_not_found(self):
        if self.request.is_ajax():
            raise Http404(_("No community is available for this domain"))
        return HttpResponseRedirect(reverse("community_not_found"))

localhub/private_messages/views.py
# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later


from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext as _
from django.views.generic import View
from rules.contrib.views import PermissionRequiredMixin
from vanilla import DeleteView, DetailView, FormView, GenericModelView, ListView

from localhub.bookmarks.models import Bookmark
from localhub.communities.views import CommunityRequiredMixin
from localhub.users.utils import user_display
from localhub.views import SearchMixin, SuccessMixin

from .forms import MessageForm
from .models import Message


class MessageQuerySetMixin(CommunityRequiredMixin):
    def get_queryset(self):
        return (
            Message.objects.for_community(community=self.request.community)
            .exclude_blocked(self.request.user)
            .common_select_related()
        )


class SenderQuerySetMixin(MessageQuerySetMixin):
    def get_queryset(self):
        return super().get_queryset().for_sender(self.request.user)


class RecipientQuerySetMixin(MessageQuerySetMixin):
    def get_queryset(self):
        return super().get_queryset().for_recipient(self.request.user)


class SenderOrRecipientQuerySetMixin(MessageQuerySetMixin):
    def get_queryset(self):
        return super().get_queryset().for_sender_or_recipient(self.request.user)


class BaseMessageListView(SearchMixin, ListView):
    paginate_by = settings.LOCALHUB_DEFAULT_PAGE_SIZE


class InboxView(RecipientQuerySetMixin, BaseMessageListView):
    """
    Messages received by current user
    oere we should show the sender, timestamp...
    """

    template_name = "private_messages/inbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by(F("read").desc(nulls_first=True), "-created")


inbox_view = InboxView.as_view()


class OutboxView(SenderQuerySetMixin, BaseMessageListView):
    """
    Messages sent by current user
    """

    template_name = "private_messages/outbox.html"

    def get_queryset(self):
        qs = super().get_queryset().with_has_bookmarked(self.request.user)
        if self.search_query:
            return qs.search(self.search_query).order_by("-rank", "-created")
        return qs.order_by("-created")


outbox_view = OutboxView.as_view()


class BaseMessageFormView(PermissionRequiredMixin, SuccessMixin, FormView):

    permission_required = "private_messages.create_message"
    template_name = "private_messages/message_form.html"
    form_class = MessageForm

    def get_permission_object(self):
        return self.request.community

    def get_success_message(self):
        return _("Your message has been sent to %(recipient)s") % {
            "recipient": self.recipient_display
        }

    @cached_property
    def recipient(self):
        return self.get_recipient()

    def get_recipient(self):
        raise NotImplementedError

    @cached_property
    def recipient_display(self):
        return user_display(self.recipient)

    def get_form(self, data=None, files=None):
        form = self.form_class(data, files)
        form["message"].label = _(
            "Send message to %(recipient)s" % {"recipient": self.recipient_display}
        )
        return form

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["recipient"] = self.recipient
        data["recipient_display"] = self.recipient_display
        return data


class BaseReplyFormView(BaseMessageFormView):
    @cached_property
    def parent(self):
        parent = get_object_or_404(self.get_queryset(), pk=self.kwargs["pk"])
        if parent.recipient == self.request.user:
            parent.mark_read()
        return parent

    def get_recipient(self):
        return self.parent.get_other_user(self.request.user)

    def notify(self):
        """Handle any notifications to recipient here"""
        ...

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["parent"] = self.parent
        return data

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.community = self.request.community
        self.object.sender = self.request.user
        self.object.recipient = self.recipient
        self.object.parent = self.parent
        self.object.save()

        self.notify()

        return self.success_response()


class MessageReplyView(RecipientQuerySetMixin, BaseReplyFormView):
    def notify(self):
        self.object.notify_on_reply()


message_reply_view = MessageReplyView.as_view()


class MessageFollowUpView(SenderQuerySetMixin, BaseReplyFormView):
    def notify(self):
        self.object.notify_on_follow_up()


message_follow_up_view = MessageFollowUpView.as_view()


class MessageCreateView(
    CommunityRequiredMixin, BaseMessageFormView,
):
    def get_recipient(self):
        return get_object_or_404(
            get_user_model()
            .objects.exclude(pk=self.request.user.id)
            .exclude(blockers=self.request.user)
            .exclude(blocked=self.request.user)
            .for_community(self.request.community),
            username=self.kwargs["username"],
        )

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.community = self.request.community
        self.object.sender = self.request.user
        self.object.recipient = self.recipient
        self.object.save()

        self.object.notify_on_send()

        return self.success_response()


message_create_view = MessageCreateView.as_view()


class MessageDetailView(SenderOrRecipientQuerySetMixin, DetailView):

    model = Message

    def get_queryset(self):
        return super().get_queryset().with_has_bookmarked(self.request.user)

    def get_object(self):
        obj = super().get_object()
        if obj.recipient == self.request.user:
            obj.mark_read(mark_replies=True)
        return obj

    def get_replies(self):
        return (
            self.object.get_all_replies()
            .for_sender_or_recipient(self.request.user)
            .common_select_related()
            .order_by("created")
            .distinct()
        )

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data.update(
            {
                "replies": self.get_replies(),
                "parent": self.object.get_parent(self.request.user),
                "other_user": self.object.get_other_user(self.request.user),
            }
        )

        return data


message_detail_view = MessageDetailView.as_view()


class MessageDeleteView(SenderOrRecipientQuerySetMixin, SuccessMixin, DeleteView):
    """
    Does a "soft delete" which sets sender/recipient deleted flag
    accordingly.

    If both sender and recipient have soft-deleted, then the message
    is "hard" deleted.
    """

    model = Message
    success_message = _("This message has been deleted")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete(self.request.user)
        return self.success_response()

    def get_success_url(self):
        if self.request.user == self.object.recipient:
            return reverse("private_messages:inbox")
        return reverse("private_messages:outbox")


message_delete_view = MessageDeleteView.as_view()


class MessageMarkReadView(RecipientQuerySetMixin, SuccessMixin, GenericModelView):
    def get_queryset(self):
        return super().get_queryset().unread()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.mark_read()
        return self.success_response()


message_mark_read_view = MessageMarkReadView.as_view()


class MessageMarkAllReadView(RecipientQuerySetMixin, View):
    def get_queryset(self):
        return super().get_queryset().unread()

    def post(self, request, *args, **kwargs):
        self.get_queryset().for_recipient(self.request.user).mark_read()
        return HttpResponseRedirect(reverse("private_messages:inbox"))


message_mark_all_read_view = MessageMarkAllReadView.as_view()


class BaseMessageBookmarkView(SenderOrRecipientQuerySetMixin, GenericModelView):
    template_name = "private_messages/includes/bookmark.html"

    def success_response(self, has_bookmarked):
        return self.render_to_response(
            {"message": self.object, "has_bookmarked": has_bookmarked}
        )


class MessageBookmarkView(BaseMessageBookmarkView):
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            Bookmark.objects.create(
                user=request.user,
                community=request.community,
                content_object=self.object,
            )
        except IntegrityError:
            pass
        return self.success_response(has_bookmarked=True)


message_bookmark_view = MessageBookmarkView.as_view()


class MessageRemoveBookmarkView(BaseMessageBookmarkView):
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        Bookmark.objects.filter(user=request.user, message=self.object).delete()
        return self.success_response(has_bookmarked=False)

    def delete(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


message_remove_bookmark_view = MessageRemoveBookmarkView.as_view()

templates/private_messages/base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "base.html" %}

{% load i18n %}
{% block subtitle %} / {% trans "Messages" %}{% endblock %}

templates/private_messages/inbox.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/message_list_base.html" %}

{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Inbox" %}{% endblock %}

{% block message_list %}
{% if paginator.count or view.search_query %}
{% include "includes/forms/search_form.html" with selector=True %}
{% endif %}

{% include "private_messages/includes/email_settings.html" %}
{% trans "You have not received any messages" as t_empty_message %}
{% include "private_messages/includes/message_list.html" with empty_message=t_empty_message %}
{% endblock message_list %}

templates/private_messages/message_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<h5>{% trans "Delete Message" %}</h5>

<form method="POST"
      action="{{ request.path }}">
  {% csrf_token %}
  <p>{% trans "Do you really want to delete this message?" %}</p>
  <a class="btn btn-link"
     href="{{ message.get_absolute_url }}">{% trans "Cancel" %}</a>
  <button class="btn btn-primary"
          type="submit">{% trans "Delete" %}</button>
</form>

{% endblock content %}

templates/private_messages/message_detail.html
{% extends "private_messages/base.html" %}

{% load i18n %}
{% load account %}
{% load rules %}
{% load private_messages_tags %}

{% block content %}

{% if parent %}
<ul class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{{ parent.get_absolute_url }}">{% trans "Parent" %}</a>
  </li>
  <li class="breadcrumb-item"><a href="#">{% trans "Message" %}</a></li>
</ul>
{% endif %}

{% has_perm "private_messages.create_message" user community as can_create_message %}

<h5>{% trans "Messages" %}</h5>

<div class="actions mb-1">
  <a href="{% url 'private_messages:inbox' %}">{% trans "Inbox" %}</a>
  <a href="{% url 'private_messages:outbox' %}">{% trans "Outbox" %}</a>
  {% if can_create_message %}
  <a href="{% url 'private_messages:message_create' other_user.username %}">
    {% user_display other_user as other_user_name %}
    {% blocktrans %}
    Send Message to {{ other_user_name }}
    {% endblocktrans %}
  </a>
  {% endif %}

</div>

{% render_message request user message is_detail=True %}
{% for reply in replies %}
{% render_message request user reply conversation=message %}
{% endfor %}
{% endblock content %}

templates/private_messages/message_form.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/base.html" %}

{% load i18n %}
{% load account %}
{% load private_messages_tags %}

{% block subtitle %} / {% user_display recipient %} / {{ parent|yesno:_("Reply,Send Message") }} {% endblock %}

{% block content %}

<ul class="breadcrumb">
  {% if parent %}
  <li class="breadcrumb-item"><a href="{{ parent.get_absolute_url }}">{% trans "Parent" %}</a></li>
  <li class="breadcrumb-item">
    <a href="#">
      {% if parent.sender == user %}{% trans "Follow-Up" %}{% else %}{% trans "Reply" %}{% endif %}
    </a>
  </li>
  {% else %}
  <li class="breadcrumb-item"><a href="{% url 'users:messages' recipient.username %}">{% user_display recipient %}</a>
  </li>
  <li class="breadcrumb-item">
    <a data-turbolinks="false"
       href="#">{% trans "Send Message" %}</a>
  </li>
  {% endif %}
</ul>


<h5>{% trans "Messages" %}</h5>

{% if parent %}
{% render_message request user parent is_detail=True %}
{% endif %}

{% include "includes/forms/stimulusjs_form.html" %}

{% endblock %}

templates/private_messages/message_list_base.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/base.html" %}

{% load i18n %}
{% load private_messages_tags %}
{% load rules %}


{% block content %}
<h5>{% trans "Messages" %}</h5>

{% has_perm "private_messages.create_message" user community as can_create_message %}
{% get_unread_message_count user community as unread_messages %}
{% if can_create_message or unread_messages %}
<div class="actions mb-1">
  {% if unread_messages %}
  <a href="{% url 'private_messages:mark_all_read' %}"
     data-controller="ajax"
     data-action="ajax#post"
     data-ajax-redirect="{{ request.get_full_path }}">{% trans "Mark All As Read" %}</a>
  {% endif %}
</div>
{% endif %}


{% with search=view.search_query %}
<ul class="tab tab-block mt-2">
  <li class="tab-item"
      data-controller="active-link"
      data-active-link-exact>
    <a data-target="active-link.match"
       href="{% url 'private_messages:inbox' %}{% if search %}?q={{ search }}{% endif %}">{% trans "Inbox" %}</a>
  </li>
  <li class="tab-item"
      data-controller="active-link"
      data-active-link-exact>
    <a data-target="active-link.match"
       href="{% url 'private_messages:outbox' %}{% if search %}?q={{ search }}{% endif %}">{% trans "Outbox" %}</a>
  </li>
</ul>
{% endwith %}

{% block message_list %}{% endblock %}

{% endblock content %}

templates/private_messages/outbox.html
{# Copyright (c) 2020 by Dan Jacob #}
{# SPDX-License-Identifier: AGPL-3.0-or-later #}

{% extends "private_messages/message_list_base.html" %}

{% load i18n %}

{% block subtitle %}{{ block.super }} / {% trans "Outbox" %}{% endblock %}

{% block message_list %}

{% if paginator.count or view.search_query %}
{% include "includes/forms/search_form.html" with selector=True %}
{% endif %}

{% trans "You have not sent any messages" as t_empty_message %}
{% include "private_messages/includes/message_list.html" with empty_message=t_empty_message %}
{% endblock message_list %}